#!/usr/bin/env bash
#display information about subdomains
function impresions(){
    dig "$1" | grep -A1 'ANSWER SECTION:'| awk '
    {
split($1,A,".")
    if (NF >= 5)
print "The subdomain " A[1] " is a " $4 " record and points to " $5
    }'
}
domain=(www lb-01 web-01 web-02)
if [[ "$#" -ne 2 ]];
then
    for i in "${domain[@]}"; do impresions "$i.$1"; done
else
    impresions "$2.$1"
fi
