#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server#
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get update
sudo apt-get install haproxy=1.8.\* -y
sudo -e "ENABLED=1\n" | sudo tee /etc/default/haproxy
echo -e "\tfrontend 757-lb-01\n \tbind 35.231.2.128:80\n \tmode http\n \tdefault_backend My_Web_Servers "|sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tbackend nodes\n \tmode http\n \tbalance roundrobin\n \tserver 757-web-01  35.243.237.179:80\n \tserver 757-web-02  35.190.141.254:80"| sudo tee -a /etc/haproxy/haproxy.cfg
sudo service nginx restart
