#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and
hour=0
while [ $hour -le 12 ]
do
    min=1
    echo "Hour: $hour"
    while [ $min -le 59 ]
    do
	echo "$min"
	min=$(( min + 1 ))
    done
    hour=$(( hour + 1 ))
done
