#!/usr/bin/env bash
# Bash script that displays ls
device0="holbertonschool"
if [[ -e "$device0" ]];
then
    echo "holbertonschool file exists"
    if [[ -s "$device0" ]];
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [[ -f "$device0" ]];
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"

fi
