#!/usr/bin/env bash
#Run software as another user
pkill apache2
sudo chown nginx /etc/nginx/nginx.conf
sudo chgrp nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo service nginx restart
