#!/usr/bin/env bash
#Run software as another user
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i -e "s/80/8080/g" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
